import { createStarterChapter, validateChapter, parseChapter, cloneChapter } from '../chapter/model.js';
import { Preview } from './preview.js';
import { saveChapter, loadChapter } from './storage.js';
const $ = s => document.querySelector(s);
const assets=['box','escape','goggles_01','pack','flashlight','corridor_02','city','hall_01'];
const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid = prefix => `${prefix}-${crypto.randomUUID().slice(0,8)}`;
const loaded=loadChapter(); let doc=loaded.chapter || createStarterChapter();
let selected=doc.startNode, undo=[],redo=[],pending=null,view={x:60,y:60,z:1},previewStart;
const preview=new Preview($('#preview'),{onRestart:()=>play(previewStart || doc.startNode),onChange:state=>{ document.querySelectorAll('.node').forEach(el=>el.classList.toggle('active',el.dataset.id===state?.activeNodeId)); }});
function commit(fn){undo.push(cloneChapter(doc));if(undo.length>80)undo.shift();redo=[];fn();persist();render();}
function persist(){const result=saveChapter(doc);$('#save-status').textContent=result.ok?'Saved in this browser':`Save failed: ${result.error}`;}
function node(){return doc.nodes.find(n=>n.id===selected)}
function sequence(){return doc.sequences.find(s=>s.id===node()?.sequenceId)}
function options(values,current){return values.map(([v,t])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(t)}</option>`).join('')}
function field(label,value,path,type='text'){return `<label class="field">${esc(label)}${type==='textarea'?`<textarea data-path="${path}">${esc(value)}</textarea>`:`<input type="${type}" data-path="${path}" value="${esc(value)}">`}</label>`}
function imageField(value,path){return `${field('Image path',value,path)}<label class="field">Existing artwork<select data-path="${path}">${options([['','Choose artwork…'],...assets.map(a=>[`./assets/img/${a}.png`,a])],value)}</select></label>`}
function exits(n){return n.type==='random'?['next']:doc.sequences.find(s=>s.id===n.sequenceId)?.exits || ['next']}
function render(){
 if(!doc.nodes.some(n=>n.id===selected))selected=doc.startNode;
 $('#chapter-name').value=doc.name;$('#undo').disabled=!undo.length;$('#redo').disabled=!redo.length;
 const issues=validateChapter(doc);$('#errors').innerHTML=issues.map(e=>`<div>${esc(e.message)}</div>`).join('');
 $('#nodes').innerHTML=doc.nodes.map(n=>{const s=doc.sequences.find(s=>s.id===n.sequenceId);return `<article class="node ${n.type} ${n.id===selected?'selected':''} ${preview.state?.activeNodeId===n.id?'active':''} ${issues.some(e=>e.nodeId===n.id)?'invalid':''}" data-id="${esc(n.id)}" style="left:${n.x}px;top:${n.y}px"><div class="node-heading"><span class="badge">${n.id===doc.startNode?'START · ':''}${n.type==='random'?'Random pool':`Static · ${s?.type || 'missing'}`}</span>${esc(n.name)}</div><div class="node-body">${n.type==='random'?`${n.count} selections · ${n.pool.length} sequences`:`${s?.cards?.length || 0} cards${s?.type==='container'?` · ${s.items.length} items`:''}`}</div>${exits(n).map(e=>`<button class="port ${pending?.nodeId===n.id && pending.exit===e?'pending':''}" data-exit="${esc(e)}">${esc(e)} → ${esc(doc.nodes.find(t=>t.id===n.connections[e])?.name || 'End')}</button>`).join('')}</article>`}).join('');
 edges();inspector();transform();
}
function transform(){$('#world').style.transform=`translate(${view.x}px,${view.y}px) scale(${view.z})`}
function edges(){ $('#edges').innerHTML=doc.nodes.flatMap(n=>exits(n).map((exit,i)=>{const t=doc.nodes.find(t=>t.id===n.connections[exit]);if(!t)return '';let x=n.x+220,y=n.y+104+i*29,tx=t.x,ty=t.y+40;return `<path d="M${x},${y} C${x+90},${y} ${tx-90},${ty} ${tx},${ty}"/>` })).join('') }
function inspector(){const n=node();$('#selected-type').textContent=n?.type || '';if(!n){$('#inspector').innerHTML='<p>Select a node to edit it.</p>';return}
 let html=field('Node name',n.name,'node.name');
 if(n.type==='random'){
 html+=field('Number of selections',n.count,'node.count','number')+'<h3>Sequence pool</h3>'+n.pool.map((p,i)=>`<div class="entry"><label class="field">Sequence<select data-path="node.pool.${i}.sequenceId">${options(doc.sequences.map(s=>[s.id,s.name]),p.sequenceId)}</select></label>${field('Weight',p.weight,`node.pool.${i}.weight`,'number')}<button data-command="remove-pool" data-index="${i}">Remove</button></div>`).join('')+'<button data-command="add-pool">+ Pool sequence</button><p class="small">Selections do not repeat within this block. Every sequence exit returns here.</p>';
 }else{const s=sequence();if(!s){$('#inspector').innerHTML=html+'Missing sequence';return}
 html+=`<label class="field">Sequence<select data-path="node.sequenceId">${options(doc.sequences.map(s=>[s.id,s.name]),s.id)}</select></label>`+field('Sequence name',s.name,'sequence.name')+`<p class="small">${doc.nodes.filter(n=>n.sequenceId===s.id).length} static node(s) use this sequence. Changes apply to every reference and pool.</p>`;
 const targets=[...s.cards.map(c=>[`card:${c.id}`,`Card: ${c.title}`]),...s.exits.map(e=>[`exit:${e}`,`Exit: ${e}`])];
 html+=s.cards.map((c,i)=>`<details class="entry" open><summary>${i+1}. ${esc(c.title)}</summary>${field('Title',c.title,`sequence.cards.${i}.title`)}${field('Description',c.text,`sequence.cards.${i}.text`,'textarea')}${imageField(c.image,`sequence.cards.${i}.image`)}${s.type==='forked'?(c.choices||[]).map((a,j)=>`<div class="entry">${field('Choice label',a.label,`sequence.cards.${i}.choices.${j}.label`)}${imageField(a.image,`sequence.cards.${i}.choices.${j}.image`)}<label class="field">Destination<select data-path="sequence.cards.${i}.choices.${j}.target">${options(targets,a.target)}</select></label><button data-command="remove-choice" data-index="${i}" data-choice="${j}">Remove choice</button></div>`).join('')+`<button data-command="add-choice" data-index="${i}" ${(c.choices||[]).length>=3?'disabled':''}>+ Choice</button>`:''}${s.type!=='container'?`<div class="row"><button data-command="up-card" data-index="${i}" ${i===0?'disabled':''}>↑</button><button data-command="down-card" data-index="${i}" ${i===s.cards.length-1?'disabled':''}>↓</button><button data-command="remove-card" data-index="${i}">Remove card</button></div>`:''}</details>`).join('');
 if(s.type!=='container')html+='<button data-command="add-card">+ Card</button>';
 if(s.type==='container')html+='<h3>Items</h3>'+s.items.map((item,i)=>`<div class="entry">${field('Item name',item.label,`sequence.items.${i}.label`)}${imageField(item.image,`sequence.items.${i}.image`)}<button data-command="remove-item" data-index="${i}">Remove item</button></div>`).join('')+'<button data-command="add-item">+ Item</button><p class="small">Up discards an item; Down takes it. Resolve every item to continue. The last item reveals the next card back.</p>';
 html+='<h3>Sequence exits</h3>'+s.exits.map((e,i)=>`<div class="row"><input aria-label="Exit name" data-path="sequence.exits.${i}" value="${esc(e)}"><button data-command="remove-exit" data-index="${i}">×</button></div>`).join('')+(s.type==='forked'?'<button data-command="add-exit">+ Named exit</button>':'');
 }
 html+='<h3>Chapter connections</h3>'+exits(n).map(e=>`<label class="field">${esc(e)}<select data-connection="${esc(e)}">${options([['','End chapter'],...doc.nodes.filter(t=>t.id!==n.id).map(t=>[t.id,t.name])],n.connections[e] || '')}</select></label>`).join('');
 html+='<p class="small">An unconnected exit ends the chapter. Cycles and incomplete references block playback.</p>';$('#inspector').innerHTML=html;
}
$('#inspector').addEventListener('change',e=>{const path=e.target.dataset.path,connection=e.target.dataset.connection;if(connection){commit(()=>node().connections[connection]=e.target.value || null);return}if(!path)return;const value=e.target.type==='number'?Number(e.target.value):e.target.value;commit(()=>{if(path.startsWith('sequence.exits.')){const seq=sequence(),index=Number(path.split('.').pop()),old=seq.exits[index];for(const card of seq.cards)for(const choice of card.choices || [])if(choice.target===`exit:${old}`)choice.target=`exit:${value}`;for(const ref of doc.nodes.filter(n=>n.sequenceId===seq.id)){ref.connections[value]=ref.connections[old] ?? null;delete ref.connections[old];}}const keys=path.split('.');let target=keys.shift()==='node'?node():sequence();while(keys.length>1)target=target[keys.shift()];target[keys[0]]=value;if(path==='node.sequenceId'){node().connections=Object.fromEntries(exits(node()).map(exit=>[exit,node().connections[exit] ?? null]));}})});
function newCard(type){const id=uid('card');return {id,title:'New situation',text:'Describe what happens.',image:'./assets/img/corridor_02.png',...(type==='forked'?{choices:[{id:uid('choice'),label:'Continue',image:'./assets/img/escape.png',target:'exit:next'},{id:uid('choice'),label:'Turn back',image:'./assets/img/escape.png',target:'exit:next'}]}:{})}}
$('#inspector').addEventListener('click',e=>{const b=e.target.closest('[data-command]');if(!b)return;const cmd=b.dataset.command,i=Number(b.dataset.index),j=Number(b.dataset.choice);commit(()=>{const s=sequence(),n=node();switch(cmd){case 'add-card':s.cards.push(newCard(s.type));break;case 'remove-card':s.cards.splice(i,1);break;case 'up-card':[s.cards[i-1],s.cards[i]]=[s.cards[i],s.cards[i-1]];break;case 'down-card':[s.cards[i+1],s.cards[i]]=[s.cards[i],s.cards[i+1]];break;case 'add-choice':s.cards[i].choices.push({id:uid('choice'),label:'New choice',image:'./assets/img/escape.png',target:`exit:${s.exits[0] || 'next'}`});break;case 'remove-choice':s.cards[i].choices.splice(j,1);break;case 'add-item':s.items.push({id:uid('item'),label:'New item',image:'./assets/img/pack.png'});break;case 'remove-item':s.items.splice(i,1);break;case 'add-exit':{const exit=`exit${s.exits.length+1}`;s.exits.push(exit);for(const ref of doc.nodes.filter(r=>r.sequenceId===s.id))ref.connections[exit]=null;}break;case 'remove-exit':{const old=s.exits.splice(i,1)[0];for(const ref of doc.nodes.filter(n=>n.sequenceId===s.id))delete ref.connections[old];break;}case 'add-pool':n.pool.push({sequenceId:doc.sequences[0]?.id || '',weight:1});break;case 'remove-pool':n.pool.splice(i,1);break}})});
function add(type){commit(()=>{const id=uid('node'),position={x:(150-view.x)/view.z,y:(140-view.y)/view.z};let n={id,name:type==='random'?'Random encounters':`New ${type}`,type:type==='random'?'random':'static',...position,connections:{next:null}};if(type==='random'){n.pool=doc.sequences.length?[{sequenceId:doc.sequences[0].id,weight:1}]:[];n.count=1}else{const s={id:uid('sequence'),name:n.name,type,cards:[newCard(type)],exits:['next']};if(type==='container')s.items=[{id:uid('item'),label:'Supplies',image:'./assets/img/pack.png'}];doc.sequences.push(s);n.sequenceId=s.id}doc.nodes.push(n);selected=id})}
for(const b of document.querySelectorAll('[data-add]'))b.onclick=()=>add(b.dataset.add);
$('#duplicate').onclick=()=>{if(!node())return;commit(()=>{const n=cloneChapter(node());n.id=uid('node');n.name+=' copy';n.x+=40;n.y+=40;if(n.type==='static'){const s=cloneChapter(sequence());s.id=uid('sequence');s.name+=' copy';doc.sequences.push(s);n.sequenceId=s.id}doc.nodes.push(n);selected=n.id})};
$('#delete').onclick=()=>{if(!node())return;commit(()=>{doc.nodes=doc.nodes.filter(n=>n.id!==selected);for(const n of doc.nodes)for(const exit in n.connections)if(n.connections[exit]===selected)n.connections[exit]=null;if(doc.startNode===selected)doc.startNode=doc.nodes[0]?.id || '';selected=doc.nodes[0]?.id;pending=null})};
$('#start').onclick=()=>{if(node())commit(()=>doc.startNode=selected)};
$('#chapter-name').onchange=e=>commit(()=>doc.name=e.target.value);
$('#undo').onclick=()=>{if(!undo.length)return;redo.push(cloneChapter(doc));doc=undo.pop();pending=null;persist();render()};$('#redo').onclick=()=>{if(!redo.length)return;undo.push(cloneChapter(doc));doc=redo.pop();persist();render()};
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${doc.name.replace(/[^a-z0-9]+/gi,'-') || 'chapter'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#import').onchange=async e=>{try{const incoming=parseChapter(await e.target.files[0].text());preview.stop();commit(()=>{doc=incoming;selected=doc.startNode});fit()}catch(error){$('#save-status').textContent=`Import rejected: ${error.message}`}e.target.value=''};
function play(start){const issues=validateChapter(doc);if(issues.length){$('#errors').innerHTML=issues.map(e=>`<div>${esc(e.message)}</div>`).join('');return}previewStart=start;try{preview.play(cloneChapter(doc),start);$('#preview').scrollIntoView({block:'start',behavior:'smooth'})}catch(e){$('#save-status').textContent=e.message}}
$('#play').onclick=()=>play(doc.startNode);$('#play-node').onclick=()=>play(selected);$('#restart').onclick=()=>play(doc.nodes.some(n=>n.id===previewStart)?previewStart:doc.startNode);$('#stop').onclick=()=>{preview.stop();document.querySelectorAll('.active').forEach(el=>el.classList.remove('active'))};
function fit(){if(!doc.nodes.length){view={x:60,y:60,z:1};transform();return}const minX=Math.min(...doc.nodes.map(n=>n.x)),minY=Math.min(...doc.nodes.map(n=>n.y)),maxX=Math.max(...doc.nodes.map(n=>n.x+220)),maxY=Math.max(...doc.nodes.map(n=>n.y+180)),rect=$('#canvas').getBoundingClientRect();view.z=Math.min(1,(rect.width-100)/(maxX-minX),(rect.height-100)/(maxY-minY));view.x=50-minX*view.z;view.y=50-minY*view.z;transform()}
$('#fit').onclick=fit;
let drag=null;
$('#canvas').addEventListener('pointerdown',e=>{if(e.button!==0)return;const el=e.target.closest('.node'),port=e.target.closest('[data-exit]');if(port){pending={nodeId:el.dataset.id,exit:port.dataset.exit};drag={kind:'wire',x:e.clientX,y:e.clientY};render();$('#canvas').setPointerCapture(e.pointerId);return}if(el){if(pending){const source=doc.nodes.find(n=>n.id===pending.nodeId);const exit=pending.exit;pending=null;commit(()=>source.connections[exit]=el.dataset.id);return}selected=el.dataset.id;render();drag={kind:'node',id:selected,x:e.clientX,y:e.clientY,ox:node().x,oy:node().y,before:cloneChapter(doc)}}else{pending=null;drag={kind:'pan',x:e.clientX,y:e.clientY,ox:view.x,oy:view.y}}$('#canvas').setPointerCapture(e.pointerId)});
$('#canvas').addEventListener('pointermove',e=>{if(!drag)return;if(drag.kind==='wire'){const r=$('#canvas').getBoundingClientRect(),n=doc.nodes.find(n=>n.id===pending.nodeId),x=n.x+220,y=n.y+104+exits(n).indexOf(pending.exit)*29,tx=(e.clientX-r.left-view.x)/view.z,ty=(e.clientY-r.top-view.y)/view.z;edges();$('#edges').insertAdjacentHTML('beforeend',`<path d="M${x},${y} L${tx},${ty}"/>`);return}if(drag.kind==='pan'){view.x=drag.ox+e.clientX-drag.x;view.y=drag.oy+e.clientY-drag.y;transform()}else{const n=doc.nodes.find(n=>n.id===drag.id);n.x=drag.ox+(e.clientX-drag.x)/view.z;n.y=drag.oy+(e.clientY-drag.y)/view.z;const el=document.querySelector(`.node[data-id="${n.id}"]`);el.style.left=`${n.x}px`;el.style.top=`${n.y}px`;edges()}});
function endDrag(e){if(drag?.kind==='wire'){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.node');if(target && target.dataset.id!==pending.nodeId){const source=doc.nodes.find(n=>n.id===pending.nodeId),exit=pending.exit;pending=null;commit(()=>source.connections[exit]=target.dataset.id);}else edges();}if(drag?.kind==='node'&&(node()?.x!==drag.ox||node()?.y!==drag.oy)){undo.push(drag.before);redo=[];persist();render()}drag=null}
$('#canvas').addEventListener('pointerup',endDrag);$('#canvas').addEventListener('pointercancel',endDrag);
$('#canvas').addEventListener('wheel',e=>{e.preventDefault();const r=$('#canvas').getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,z=Math.max(.25,Math.min(2,view.z*Math.exp(-e.deltaY*.001)));view.x=x-(x-view.x)*z/view.z;view.y=y-(y-view.y)*z/view.z;view.z=z;transform()},{passive:false});
document.addEventListener('keydown',e=>{if(e.key==='Escape' && !e.target.closest('#preview')){pending=null;drag=null;render()}if(e.target.matches('input,textarea,select'))return;if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();$(e.shiftKey?'#redo':'#undo').click()}});
persist();render();fit();if(loaded.error)$('#save-status').textContent=`Saved chapter unavailable: ${loaded.error}`;
