import { esc, options } from './fields.js';
const input=(label,value,path,kind='text')=>`<label class="field">${esc(label)}<input type="${kind==='number'?'number':'text'}" data-path="${path}" ${kind==='number'?'step="any"':''} value="${esc(value)}"></label>`;
const select=(label,values,value,path,extra='')=>`<label class="field">${esc(label)}<select data-path="${path}" ${extra}>${options(values,value)}</select></label>`;
const valueField=(value,path,type)=>type==='flag'?select('Value',[['true','True'],['false','False']],String(value),path,'data-value-type="flag"'):input('Value',value,path,'number');
const variables=doc=>(doc.variables||[]).map(v=>[v.id,v.id]);
const items=doc=>[...new Map(doc.sequences.flatMap(s=>(s.items||[]).map(i=>[i.id,i.label]))).entries()];
const safeOptions=(list,value)=>list.some(([id])=>id===value)?list:[...list,[value,`Missing: ${value}`]];
export function renderVariables(doc){
 return `<details class="state-panel" data-state-section="variables"><summary>Run variables · ${(doc.variables||[]).length}</summary><p class="small">Flags and numbers reset on restart. Names use letters, numbers and underscores.</p>${(doc.variables||[]).map((v,i)=>`<div class="entry state-row">${input('Name',v.id,`chapter.variables.${i}.id`)}${select('Type',[['flag','Flag'],['number','Number']],v.type,`chapter.variables.${i}.type`,'data-variable-type="'+i+'"')}${valueField(v.initial,`chapter.variables.${i}.initial`,v.type)}<button data-state-command="remove-variable" data-index="${i}">Remove variable</button></div>`).join('')}<button data-state-command="add-variable">+ Variable</button></details>`;
}
export function renderRules(target,path,doc,{conditions=false}={}){
 const effects=target.effects||[], rules=target.conditions||[];
 return `<details class="state-panel" data-state-section="${path}"><summary>${conditions?'Conditions & effects':'Effects'} · ${rules.length+effects.length}</summary><p class="small">${conditions?'All conditions must be met. Effects apply once when this choice is accepted.':path.includes('.items.')?'Effects apply when the item is taken, after its departure. Discarding applies none.':'Effects apply when this story card is swiped away.'}</p>${conditions?`<h4>Conditions</h4>${rules.map((r,i)=>{
 const base=`${path}.conditions.${i}`, variable=doc.variables?.find(v=>v.id===r.key), inventory=r.source==='inventory';
 return `<div class="entry">${select('Check',[['variable','Variable'],['inventory','Inventory item']],r.source,base+'.source',`data-rule-source="${base}"`)}${select(inventory?'Item':'Variable',safeOptions(inventory?items(doc):variables(doc),r.key),r.key,base+'.key',`data-rule-key="${base}"`)}${select('Comparison',inventory?[['has','Owned'],['missing','Not owned']]:variable?.type==='flag'?[['eq','Equals'],['neq','Does not equal']]:[['eq','Equals'],['neq','Does not equal'],['gte','At least'],['lte','At most']],r.op,base+'.op')}${inventory?'':valueField(r.value,base+'.value',variable?.type||'number')}<button data-state-command="remove-condition" data-state-path="${path}" data-index="${i}">Remove condition</button></div>`;
 }).join('')}<button data-state-command="add-condition" data-state-path="${path}" ${!variables(doc).length&&!items(doc).length?'disabled':''}>+ Condition</button>${select('When requirements are not met',[['disabled','Show unavailable'],['hidden','Hide choice']],target.unavailable||'disabled',path+'.unavailable')}`:''}<h4>Effects</h4>${effects.map((r,i)=>{
 const base=`${path}.effects.${i}`,variable=doc.variables?.find(v=>v.id===r.key);
 return `<div class="entry">${select('Variable',safeOptions(variables(doc),r.key),r.key,base+'.key',`data-effect-key="${base}"`)}${select('Change',variable?.type==='flag'?[['set','Set']]:[['set','Set'],['add','Add / subtract']],r.op,base+'.op')}${valueField(r.value,base+'.value',variable?.type||'number')}<button data-state-command="remove-effect" data-state-path="${path}" data-index="${i}">Remove effect</button></div>`;
 }).join('')}${!variables(doc).length?'<p class="small">Effects change run variables. Create your first variable here, then name it in Chapter settings → Run variables.</p>':''}<button data-state-command="add-effect" data-state-path="${path}">${variables(doc).length?'+ Effect':'+ Create variable & effect'}</button></details>`;
}
